In [1]:
import os
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium import webdriver
from selenium.webdriver.common.by import By
import re
import pandas as pd
options = Options()
options.headless = True
service = Service(executable_path="chromium.chromedriver")
driver = webdriver.Chrome(options=options, service=service)
from bs4 import BeautifulSoup
import requests

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

In [2]:
import re
import numpy as np

In [3]:
driver.get("https://yalebulldogs.com")
links = driver.find_elements("tag name", "a")

In [4]:
url = "https://yalebulldogs.com"
href_list = []
url += "/sports"
sports = ["football","basketball","field","volleyball","soccer"]
for link in links:
    try:
        href = link.get_attribute("href")
        href_split_slash = href.split("/")
        href_sports = href_split_slash[-1].split("-")
        href_sport = href_sports[-1]
        href += "/roster"
        if re.match(url,href) and href not in href_list and href_sport in sports:
            href_list.append(href)
    except:
        continue

In [5]:
href_list.pop(4)

'https://yalebulldogs.com/sports/mens-soccer/roster'

In [6]:
href_list

['https://yalebulldogs.com/sports/womens-basketball/roster',
 'https://yalebulldogs.com/sports/womens-soccer/roster',
 'https://yalebulldogs.com/sports/womens-track-and-field/roster',
 'https://yalebulldogs.com/sports/womens-volleyball/roster',
 'https://yalebulldogs.com/sports/mens-track-and-field/roster',
 'https://yalebulldogs.com/sports/mens-basketball/roster',
 'https://yalebulldogs.com/sports/football/roster']

In [7]:
two_year_list = ["2010-11", "2011-12", "2012-13", "2013-14", 
                 "2014-15","2015-16","2016-17","2018-19",
                 "2019-20","2020-21", "2021-22", "2022-23", "2023-24"]
year_list = ["2010", "2011", "2012", "2013", "2014", "2015", "2016", 
             "2017", "2018", "2019", "2020", "2021", "2022", "2023"]
two_year_sports = ['https://yalebulldogs.com/sports/womens-basketball/roster',
                  'https://yalebulldogs.com/sports/womens-track-and-field/roster',
                   'https://yalebulldogs.com/sports/mens-track-and-field/roster',
                   'https://yalebulldogs.com/sports/mens-basketball/roster'
                  'https://yalebulldogs.com/sports/mens-soccer/roster']
one_year_sports = ['https://yalebulldogs.com/sports/womens-soccer/roster',
                  'https://yalebulldogs.com/sports/womens-volleyball/roster',
                  'https://yalebulldogs.com/sports/football/roster']

In [8]:
merge_list = []
for href in href_list:
    if href in two_year_sports:
        for year in two_year_list:
            href_year = href + "/" + year
            df = pd.read_html(href_year)[2]
            df["year"] = year
            df["team"] = re.findall("//.*/.*/(.*)/.*$", href)[0].replace("-", " ")
            merge_list.append(df)
    if href in one_year_sports:
        for year in year_list:
            href_year = href + "/" + year
            df = pd.read_html(href_year)[2]
            df["year"] = year
            df["team"] = re.findall("//.*/.*/(.*)/.*$", href)[0].replace("-", " ")
            merge_list.append(df)
full_df = pd.concat(merge_list)

In [9]:
full_df

,#,Full Name,Pos,Ht.,Academic Year,Hometown / High School,year,team,No.,Name,Pos.,Cl.,Events,Major,Hometown / High School / Club,Club,Wt.,Custom Field 1
0,3.0,Janna Graf,F,6-,Fy.,"Mission Woods, Kan. / Shawnee Mission E.",2010-11,womens basketball,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10.0,Yoyo Greenfield,G,5-5,Sr.,"Los Angeles, Calif. / Harvard Westlake",2010-11,womens basketball,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11.0,Zenab Keita,C,6-2,Fy.,"Raleigh, N.C. / Pomfret School",2010-11,womens basketball,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13.0,Verena Lehner,G/F,6-1,Jr.,"Gmunden, Austria / Pomfret School",2010-11,womens basketball,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,14.0,Allie Messimer,G,5-8,So.,"The Woodlands, Texas / College Park",2010-11,womens basketball,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,6-7,NaN,"West Palm Beach, Fla. / The Benjamin School",2023,football,64.0,Andrew Weisz,OL,Jr.,NaN,NaN,NaN,NaN,316.0,Political Science
116,NaN,NaN,NaN,6-2,NaN,"Ypsilanti, Mich. / Lincoln",2023,football,41.0,Melik Williams,LB,So.,NaN,NaN,NaN,NaN,231.0,Undeclared
117,NaN,NaN,NaN,6-5,NaN,"Stuttgart, Germany / Cheshire Academy",2023,football,65.0,Lukas Witt,OL,Fy.,NaN,NaN,NaN,NaN,267.0,Economics
118,NaN,NaN,NaN,6-3,NaN,"Airmont, N.Y. / Suffern",2023,football,98.0,Dylan Yang,DL,So.,NaN,NaN,NaN,NaN,273.0,Undeclared
119,NaN,NaN,NaN,6-4,NaN,"Vienna, Va. / James Madison",2023,football,44.0,Ry Yates,TE,Jr.,NaN,NaN,NaN,NaN,246.0,Economics

In [10]:
soccer_list = ["2010-11", "2011-12", "2012-13", "2013-14", 
                 "2014-15","2015-16","2016-17","2018-19",
                 "2019-20","2020-21", "2021", "2022", "2023"]

In [11]:
href = 'https://yalebulldogs.com/sports/mens-soccer/roster'
merge_list = []
for year in soccer_list:
    href_year = href + "/" + year
    df = pd.read_html(href_year)[2]
    df = pd.read_html(href_year)[2]
    df["team"] = re.findall("//.*/.*/(.*)/.*$", href)[0].replace("-", " ")
    merge_list.append(df)
soccer_df = pd.concat(merge_list)
soccer_df

,#,Full Name,Pos,Ht.,Academic Year,Hometown / High School,team,No.,Name,Pos.,Cl.,Wt.
0,0.0,Sam Obletz,GK,6-5,Fy.,"Portland, OR / Oregon Episcopal",mens soccer,NaN,NaN,NaN,NaN,NaN
1,0.0,Matt Chesky,GK,6-2,Jr.,"Holyoke, MA / Deerfield Academy",mens soccer,NaN,NaN,NaN,NaN,NaN
2,1.0,Bobby Thalman,GK,6-5,So.,"Greenwood Village, CO / Colorado Academy",mens soccer,NaN,NaN,NaN,NaN,NaN
3,2.0,Marcus DiLallo,D,6-2,Jr.,"Wellington, FL / Wellington",mens soccer,NaN,NaN,NaN,NaN,NaN
4,3.0,Andy Shorten,M,5-10,Sr.,"Hudson, OH / Western Reserve Academy",mens soccer,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
26,NaN,NaN,NaN,6-1,NaN,"Kings Point, N.Y. / Great Neck North",mens soccer,27.0,Simon Adjakple,F/M,Fy.,165.0
27,NaN,NaN,NaN,5-8,NaN,"Hopkinton, N.H. / St. Paul's School",mens soccer,28.0,Nick Miller,D,Fy.,170.0
28,NaN,NaN,NaN,6-6,NaN,"Kassel, Germany / Northfield Mount Hermon",mens soccer,29.0,Constantin Jung,GK,Fy.,205.0
29,NaN,NaN,NaN,5-10,NaN,"Boxford, Mass. / Milton Academy",mens soccer,32.0,Aydin Jay,F/M,So.,155.0
30,NaN,NaN,NaN,5-11,NaN,"Ellington, Conn. / Ellington",mens soccer,34.0,Diego Zaffanella,M,So.,175.0

In [27]:
complete_df = pd.concat([soccer_df, full_df])

In [30]:
#Yale Processing
import pandas as pd
import numpy as np
complete_df["Number"] = complete_df["#"]

df2 = complete_df

zero_list = list(df2[df2["Number"] == 0.0].index)

df2["Name"] = df2["Full Name"].fillna("") + df2["Name"].fillna("")

def number(row):
    if row["Number"] != np.NaN:
        return row["Number"]
    else:
        return row["No."]

df2["Number"] = df2["Number"].fillna(0)
df2["No."] = df2["No."].fillna(0)

df2["Number"] = df2["Number"] + df2["No."]

df2 = df2.drop(columns = ["No.","Events", "Major", "Club","Custom Field 1"])

df2[["Academic Year", "Pos", "Cl.", "Pos."]] = df2[["Academic Year", "Pos", "Cl.", "Pos."]].fillna("")

df2["Academic Year"] = df2["Academic Year"] + df2["Cl."]

df2["Position"] = df2["Pos"] + df2["Pos."]

df2["Hometown / High School / Club"] = df2["Hometown / High School / Club"].fillna("")

df2[["Hometown / High School / Club","Hometown / High School"]] = df2[["Hometown / High School / Club","Hometown / High School"]].fillna("")

df2["Hometown/Highschool"] = df2["Hometown / High School / Club"] + df2["Hometown / High School"]

def split_hometown(row):
    split = row["Hometown/Highschool"].split("/")
    strip = split[0].strip()
    return strip

df2["Hometown"] = df2.apply(split_hometown, axis = 1)

def split_highschool(row):
    split = row["Hometown/Highschool"].split("/")
    strip = split[-1].strip()
    return strip



df2["Highschool"] = df2.apply(split_highschool, axis = 1)

df2 = df2.drop(columns = ["Pos","Hometown / High School","Cl.","Hometown / High School / Club","Hometown/Highschool"])

df2 = df2.drop(columns = "Full Name")

df2["Number"] = df2["Number"].replace(to_replace = 0,value = np.NaN)

df2 = df2.drop(columns = "Pos.")


for idx in zero_list:
    df2["Number"][idx] = 0

df2["Height"] = df2["Ht."]
df2["Team"] = df2["team"]
df2["Year"] = df2["year"]
df2["Weight"] = df2["Wt."]
df2= df2.drop(columns = ["Ht.","team","year","Wt."])

df2["Number"] = df2["Number"].fillna(30000000)


df2["Number"] = df2["Number"].replace(to_replace = 30000000 ,value = np.NaN)

df2["Height"] = df2["Height"].replace(to_replace = "-" ,value = np.NaN)

df2.to_csv("yale.csv")

/tmp/ipykernel_171906/3274687899.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Number"][idx] = 0

,#,Academic Year,Name,Number,Position,Hometown,Highschool,Height,Team,Year,Weight
0,0.0,Fy.,Sam Obletz,0.0,GK,"Portland, OR",Oregon Episcopal,6-5,mens soccer,NaN,NaN
1,0.0,Jr.,Matt Chesky,0.0,GK,"Holyoke, MA",Deerfield Academy,6-2,mens soccer,NaN,NaN
2,1.0,So.,Bobby Thalman,1.0,GK,"Greenwood Village, CO",Colorado Academy,6-5,mens soccer,NaN,NaN
3,2.0,Jr.,Marcus DiLallo,2.0,D,"Wellington, FL",Wellington,6-2,mens soccer,NaN,NaN
4,3.0,Sr.,Andy Shorten,3.0,M,"Hudson, OH",Western Reserve Academy,5-10,mens soccer,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,Jr.,Andrew Weisz,64.0,OL,"West Palm Beach, Fla.",The Benjamin School,6-7,football,2023,316.0
116,NaN,So.,Melik Williams,41.0,LB,"Ypsilanti, Mich.",Lincoln,6-2,football,2023,231.0
117,NaN,Fy.,Lukas Witt,65.0,OL,"Stuttgart, Germany",Cheshire Academy,6-5,football,2023,267.0
118,NaN,So.,Dylan Yang,98.0,DL,"Airmont, N.Y.",Suffern,6-3,football,2023,273.0
119,NaN,Jr.,Ry Yates,44.0,TE,"Vienna, Va.",James Madison,6-4,football,2023,246.0

In [ ]:
two_year_list = ["2010-11", "2011-12", "2012-13", "2013-14", 
                 "2014-15","2015-16","2016-17","2018-19",
                 "2019-20","2020-21", "2021-22", "2022-23", "2023-24"]
year_list = ["2010", "2011", "2012", "2013", "2014", "2015", "2016", 
             "2017", "2018", "2019", "2020", "2021", "2022", "2023"]
two_year_sports_brown_men = ['https://brownbears.com/sports/mens-basketball/roster'
                  'https://brownbears.com/sports/mens-soccer/roster']
two_year_sports_brown_women = ['https://brownbears.com/sports/womens-basketball/roster']
one_year_sports_brown = ['https://brownbears.com/sports/womens-soccer/roster',
                  'https://brownbears.com/sports/womens-volleyball/roster']

In [ ]:
#women's soccer and volleyball
merge_list = []
for team in one_year_sports_brown:
    for year in year_list:
        url = team + "/" + year
        response = requests.get(url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
        player_names = []
        player_positions = []
        player_number = []
        player_height = []
        player_year = []
        player_weight = []
        player_home = []
        player_school = []
        player_list = soup.find_all("div", class_ = "s-person-card s-person-card--list flex flex-col overflow-hidden rounded-[10px] border s-person-card--theme-light-theme shadow-level-1 border")
        for player in player_list:
            span_list = player.find_all("span")
            if len(span_list) < 13:
                continue
            player_number.append(span_list[0].text)
            player_names.append(span_list[1].text)
            player_positions.append(span_list[2].text[9:])
            player_year.append(span_list[4].text[14:])
            player_height.append(span_list[6].text[6:])
            player_home.append(span_list[9].text[9:])
            player_school.append(span_list[11].text[12:])
        df_dict = {}
        df_dict["Name"] = player_names
        df_dict["Position"] = player_positions
        df_dict["Number"] = player_number
        df_dict["Height"] = player_height
        df_dict["Academic Year"] = player_year
        df_dict["Hometown"] = player_home
        df_dict["Highschool"] = player_school
        df = pd.DataFrame(df_dict)
        df["Team"] = re.findall("sports/(.*)/roster", url)[0].replace("-", " ")
        df["Weight"] = np.NaN
        df["Year"] = year
        merge_list.append(df)
womens_one_year_df = pd.concat(merge_list)

In [ ]:
#womens basketball
merge_list = []
for team in ["https://brownbears.com/sports/womens-basketball/roster"]:
    for year in two_year_list:
        url = team + "/" + year
        response = requests.get(url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
        player_names = []
        player_positions = []
        player_number = []
        player_height = []
        player_year = []
        player_weight = []
        player_home = []
        player_school = []
        player_list = soup.find_all("div", class_ = "s-person-card s-person-card--list flex flex-col overflow-hidden rounded-[10px] border s-person-card--theme-light-theme shadow-level-1 border")
        for player in player_list:
            span_list = player.find_all("span")
            if len(span_list) < 13:
                continue
            player_number.append(span_list[0].text)
            player_names.append(span_list[1].text)
            player_positions.append(span_list[2].text[9:])
            player_year.append(span_list[4].text[14:])
            player_height.append(span_list[6].text[6:])
            player_home.append(span_list[9].text[9:])
            player_school.append(span_list[11].text[12:])
        df_dict = {}
        df_dict["Name"] = player_names
        df_dict["Position"] = player_positions
        df_dict["Number"] = player_number
        df_dict["Height"] = player_height
        df_dict["Academic Year"] = player_year
        df_dict["Hometown"] = player_home
        df_dict["Highschool"] = player_school
        df = pd.DataFrame(df_dict)
        df["Team"] = re.findall("sports/(.*)/roster", url)[0].replace("-", " ")
        df["Weight"] = np.NaN
        df["Year"] = year
        merge_list.append(df)
womens_basketball = pd.concat(merge_list)

In [ ]:
#Football
sport = "https://brownbears.com/sports/football/roster"    
merge_football = []
for year in ["2010", "2011", "2012", "2013", "2014", "2015", "2016", 
             "2017", "2018", "2019", "2020", "2021", "2022", "2023"]:
    url = sport + "/" + year
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
    player_names = []
    player_positions = []
    player_number = []
    player_height = []
    player_year = []
    player_weight = []
    player_home = []
    player_school = []
    player_list = soup.find_all("div", class_ = "s-person-card s-person-card--list flex flex-col overflow-hidden rounded-[10px] border s-person-card--theme-light-theme shadow-level-1 border")
    for player in player_list:
        span_list = player.find_all("span")
        if len(span_list) < 13:
            continue
        player_number.append(span_list[0].text)
        player_names.append(span_list[1].text)
        player_positions.append(span_list[2].text[9:])
        player_year.append(span_list[4].text[14:])
        player_height.append(span_list[6].text[6:])
        player_weight.append(span_list[9].text.strip())
        player_home.append(span_list[10].text[9:])
        player_school.append(span_list[12].text[12:])
    df_dict = {}
    df_dict["Name"] = player_names
    df_dict["Position"] = player_positions
    df_dict["Number"] = player_number
    df_dict["Height"] = player_height
    df_dict["Academic Year"] = player_year
    df_dict["Hometown"] = player_home
    df_dict["Highschool"] = player_school
    df_dict["Weight"] = player_weight
    df = pd.DataFrame(df_dict)
    df["Year"] = year
    df["Team"] = re.findall("sports/(.*)/roster", url)[0].replace("-", " ")
    merge_football.append(df)
football_df = pd.concat(merge_football)

In [ ]:
#MensBasketball
sport = "https://brownbears.com/sports/mens-basketball/roster"    
merge_mens_basketball = []
for year in ["2010-11", "2011-12", "2012-13", "2013-14", 
                 "2014-15","2015-16","2016-17","2018-19",
                 "2019-20","2020-21", "2021-22", "2022-23", "2023-24"]:
    url = sport + "/" + year
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
    player_names = []
    player_positions = []
    player_number = []
    player_height = []
    player_year = []
    player_weight = []
    player_home = []
    player_school = []
    player_list = soup.find_all("div", class_ = "s-person-card s-person-card--list flex flex-col overflow-hidden rounded-[10px] border s-person-card--theme-light-theme shadow-level-1 border")
    for player in player_list:
        span_list = player.find_all("span")
        if len(span_list) < 13:
            continue
        player_number.append(span_list[0].text)
        player_names.append(span_list[1].text)
        player_positions.append(span_list[2].text[9:])
        player_year.append(span_list[4].text[14:])
        player_height.append(span_list[6].text[6:])
        player_weight.append(span_list[9].text.strip())
        player_home.append(span_list[10].text[9:])
        player_school.append(span_list[12].text[12:])
    df_dict = {}
    df_dict["Name"] = player_names
    df_dict["Position"] = player_positions
    df_dict["Number"] = player_number
    df_dict["Height"] = player_height
    df_dict["Academic Year"] = player_year
    df_dict["Hometown"] = player_home
    df_dict["Highschool"] = player_school
    df_dict["Weight"] = player_weight
    df = pd.DataFrame(df_dict)
    df["Year"] = year
    df["Team"] = re.findall("sports/(.*)/roster", url)[0].replace("-", " ")
    merge_mens_basketball.append(df)
mens_basketball_df = pd.concat(merge_mens_basketball)

In [ ]:
mens_basketball_df

In [ ]:
#Track and Field
tf_merge_list = []
t_f = ["https://brownbears.com/sports/womens-track-and-field/roster", "https://brownbears.com/sports/mens-track-and-field/roster"]
for sport in t_f:
    for year in two_year_list:
        url = sport + "/" + year
        response = requests.get(url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
        player_names = []
        player_positions = []
        player_number = []
        player_height = []
        player_year = []
        player_weight = []
        player_home = []
        player_school = []
        player_list = soup.find_all("div", class_ = "s-person-card s-person-card--list flex flex-col overflow-hidden rounded-[10px] border s-person-card--theme-light-theme shadow-level-1 border")
        for player in player_list:
            span_list = player.find_all("span")
            if len(span_list) < 9:
                continue
            player_names.append(span_list[0].text)
            player_positions.append(span_list[1].text[9:])
            player_year.append(span_list[3].text[14:])
            player_home.append(span_list[6].text[9:])
            player_school.append(span_list[8].text[12:])
        df_dict = {}
        df_dict["Name"] = player_names
        df_dict["Position"] = player_positions
        df_dict["Academic Year"] = player_year
        df_dict["Hometown"] = player_home
        df_dict["Highschool"] = player_school
        df = pd.DataFrame(df_dict)
        df["Height"] = np.NaN
        df["Weight"] = np.NaN
        df["Number"] = np.NaN
        df["Team"] = re.findall("sports/(.*)/roster", url)[0].replace("-", " ")
        df["Year"] = year
        tf_merge_list.append(df)
tf_df = pd.concat(tf_merge_list)
tf_df

In [ ]:
sport = "https://brownbears.com/sports/mens-soccer/roster"    
merge_msoccer = []
for year in ["2010", "2011", "2012", "2013", "2014", "2015", "2016", 
             "2017", "2018", "2019", "2020", "2021"]:
    url = sport + "/" + year
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
    player_names = []
    player_positions = []
    player_number = []
    player_height = []
    player_year = []
    player_weight = []
    player_home = []
    player_school = []
    player_list = soup.find_all("div", class_ = "s-person-card s-person-card--list flex flex-col overflow-hidden rounded-[10px] border s-person-card--theme-light-theme shadow-level-1 border")
    for player in player_list:
        span_list = player.find_all("span")
        if len(span_list) < 13:
            continue
        player_number.append(span_list[0].text)
        player_names.append(span_list[1].text)
        player_positions.append(span_list[2].text[9:])
        player_year.append(span_list[4].text[14:])
        player_height.append(span_list[6].text[6:])
        player_weight.append(span_list[9].text.strip())
        player_home.append(span_list[10].text[9:])
        player_school.append(span_list[12].text[12:])
    df_dict = {}
    df_dict["Name"] = player_names
    df_dict["Position"] = player_positions
    df_dict["Number"] = player_number
    df_dict["Height"] = player_height
    df_dict["Academic Year"] = player_year
    df_dict["Hometown"] = player_home
    df_dict["Highschool"] = player_school
    df_dict["Weight"] = player_weight
    df = pd.DataFrame(df_dict)
    df["Year"] = year
    df["Team"] = re.findall("sports/(.*)/roster", url)[0].replace("-", " ")
    merge_msoccer.append(df)
msoccer_df_2010_2021 = pd.concat(merge_msoccer)

In [ ]:
sport = "https://brownbears.com/sports/mens-soccer/roster"    
merge_msoccer = []
for year in ["2022","2023"]:
    url = sport + "/" + year
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
    player_names = []
    player_positions = []
    player_number = []
    player_height = []
    player_year = []
    player_weight = []
    player_home = []
    player_school = []
    player_list = soup.find_all("div", class_ = "s-person-card s-person-card--list flex flex-col overflow-hidden rounded-[10px] border s-person-card--theme-light-theme shadow-level-1 border")
    for player in player_list:
        span_list = player.find_all("span")
        if len(span_list) < 13:
            continue
        player_number.append(span_list[0].text)
        player_names.append(span_list[1].text)
        player_positions.append(span_list[2].text[9:])
        player_year.append(span_list[4].text[14:])
        player_home.append(span_list[7].text[9:])
        player_school.append(span_list[9].text[12:])
    df_dict = {}
    df_dict["Name"] = player_names
    df_dict["Position"] = player_positions
    df_dict["Number"] = player_number
    df_dict["Academic Year"] = player_year
    df_dict["Hometown"] = player_home
    df_dict["Highschool"] = player_school
    df = pd.DataFrame(df_dict)
    df["Year"] = year
    df["Team"] = re.findall("sports/(.*)/roster", url)[0].replace("-", " ")
    df["Weight"] = np.NaN
    df["Height"] = np.NaN
    merge_msoccer.append(df)
msoccer_df_2022_2023 = pd.concat(merge_msoccer)

In [ ]:
url = "https://brownbears.com/sports/womens-basketball/roster"
response = requests.get(url)
if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')
player_list = soup.find_all("div", class_ = "s-person-card s-person-card--list flex flex-col overflow-hidden rounded-[10px] border s-person-card--theme-light-theme shadow-level-1 border")
text_list = player_list[1].find_all("span")
text = [player.text for player in text_list]
text

In [ ]:
brown_df = pd.concat([msoccer_df_2010_2021, msoccer_df_2022_2023, tf_df,mens_basketball_df, 
                      football_df, womens_basketball, womens_one_year_df])

In [ ]:
brown_df.to_csv("Brown.csv")