In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("harvard_penn_complete.csv")

In [3]:
df = df.drop("Unnamed: 0", axis = 1)

In [4]:
df

,Name,Sport,College,Position,Height,Weight,Academic Year,Hometown,High School,Year
0,Zezo Beshir,mens-track-and-field,University of Pennsylvania,Throws,NaN,NaN,Fr.,"Newton, Mass.",Newton South,2023
1,Alex Boyko,mens-track-and-field,University of Pennsylvania,Distance,NaN,NaN,Fr.,"Cinnaminson, N.J.",Cinnaminson,2023
2,Titus Bretzke,mens-track-and-field,University of Pennsylvania,Mid-Distance,NaN,NaN,Jr.,"Greenville, Mich.",Greenville,2023
3,Nick Carpenter,mens-track-and-field,University of Pennsylvania,Distance,NaN,NaN,So.,"Winter Park, Fla.",Trinity Prep,2023
4,Elijah Cook,mens-track-and-field,University of Pennsylvania,Throws,NaN,NaN,Jr.,"Bedford, Pa.",Bedford,2023
...,...,...,...,...,...,...,...,...,...,...
8846,Cara Salsberry,track-and-field,Harvard,Throws,NaN,NaN,Jr.,"Boynton Beach, Fla.",Somerset Academy Canyons,2023
8847,Meaghan Toscano,track-and-field,Harvard,Throws,NaN,NaN,Sr.,"Lower Gwynedd, Pa.",Germantown Academy,2023
8848,Fieke Van der Kamp,track-and-field,Harvard,Distance,NaN,NaN,Fy,"Victoria, Australia",Nillumbuk High School,2023
8849,Abby Weber,track-and-field,Harvard,Distance,NaN,NaN,Fy,"Chapel Hill, N.C.",Chapel Hill High School,2023
8850,Milina Wepiwé,track-and-field,Harvard,Throws,NaN,NaN,Fy,"Friedrichsdorf, Germany",Kaiserin-Friedrich Gymnasium,2023

In [5]:
def stand_city_name(city):
    us_state_abbrev = {
        'ALA.': 'Alabama',
        'AK.': 'Alaska',
        'ARIZ.': 'Arizona',
        'AR.': 'Arkansas',
        'CALIF.': 'California',
        'COLO.': 'Colorado',
        'CONN.': 'Connecticut',
        'D.C.': 'District of Columbia',
        'DE.': 'Delaware',
        'FLA.': 'Florida',
        'GA.': 'Georgia',
        'HI.': 'Hawaii',
        'ID.': 'Idaho',
        'ILL.': 'Illinois',
        'IND.': 'Indiana',
        'IA.': 'Iowa',
        'KAN.': 'Kansas',
        'KY.': 'Kentucky',
        'LA.': 'Louisiana',
        'ME.': 'Maine',
        'MD.': 'Maryland',
        'MASS.': 'Massachusetts',
        'MICH.': 'Michigan',
        'MINN.': 'Minnesota',
        'MS.': 'Mississippi',
        'MO.': 'Missouri',
        'MT.': 'Montana',
        'NE.': 'Nebraska',
        'NEV.': 'Nevada',
        'N.H.': 'New Hampshire',
        'N.J.': 'New Jersey',
        'N.M.': 'New Mexico',
        'N.Y.': 'New York',
        'N.C.': 'North Carolina',
        'N.D.': 'North Dakota',
        'OH.': 'Ohio',
        'OKLA.': 'Oklahoma',
        'ORE.': 'Oregon',
        'PA.': 'Pennsylvania',
        'R.I.': 'Rhode Island',
        'S.C.': 'South Carolina',
        'S.D.': 'South Dakota',
        'TENN.': 'Tennessee',
        'TX.': 'Texas',
        'UT.': 'Utah',
        'VT.': 'Vermont',
        'VA.': 'Virginia',
        'WASH.': 'Washington',
        'W.V.': 'West Virginia',
        'WIS.': 'Wisconsin',
        'WY.': 'Wyoming',
        'del.': 'Delaware',
        'fl.': 'Florida',
        'miss.': 'Mississippi',
        'calif': 'California',
        'fl.': 'Florida',
        'ill.': 'Illinois',
        'tex.':'Texas',
        'il':'Illinois',
        'ks':'Kansas',
        'wa.':'Washington',
        'wva.':'West Virginia',
        'or':'Oregon',
        'wash':'Washington',
        'il.':'Illinois',
        'ga':'Georgia',
        'oh':'Ohio',
        'ct.':'Connecticut',
        'or.':'Oregon',
        'ny':'New York',
        'penn.':'Pennsylvania',
        'wisc.':'Wisconsin',
        'neb.':'Nebraska',
        'w.va.':'West Virginia',
        'mont.':'Montana',
        'ark.': 'Arkansas',
        'del.': 'Delaware'  
    }
    if city is None or not isinstance(city, str) or ',' not in city:
        return None

    city_parts  = city.split(", ")
    city_name = city_parts[0].strip().lower()
    
    if len(city_parts) < 2:
        return city_name
    
    state_abbr = city_parts[1].strip().lower()
    state_name = us_state_abbrev.get(state_abbr.upper(), state_abbr)
    
    return f"{city_name}, {state_name.lower()}"


df['std_city_name'] = df['Hometown'].apply(stand_city_name)

In [6]:
df

,Name,Sport,College,Position,Height,Weight,Academic Year,Hometown,High School,Year,std_city_name
0,Zezo Beshir,mens-track-and-field,University of Pennsylvania,Throws,NaN,NaN,Fr.,"Newton, Mass.",Newton South,2023,"newton, massachusetts"
1,Alex Boyko,mens-track-and-field,University of Pennsylvania,Distance,NaN,NaN,Fr.,"Cinnaminson, N.J.",Cinnaminson,2023,"cinnaminson, new jersey"
2,Titus Bretzke,mens-track-and-field,University of Pennsylvania,Mid-Distance,NaN,NaN,Jr.,"Greenville, Mich.",Greenville,2023,"greenville, michigan"
3,Nick Carpenter,mens-track-and-field,University of Pennsylvania,Distance,NaN,NaN,So.,"Winter Park, Fla.",Trinity Prep,2023,"winter park, florida"
4,Elijah Cook,mens-track-and-field,University of Pennsylvania,Throws,NaN,NaN,Jr.,"Bedford, Pa.",Bedford,2023,"bedford, pennsylvania"
...,...,...,...,...,...,...,...,...,...,...,...
8846,Cara Salsberry,track-and-field,Harvard,Throws,NaN,NaN,Jr.,"Boynton Beach, Fla.",Somerset Academy Canyons,2023,"boynton beach, florida"
8847,Meaghan Toscano,track-and-field,Harvard,Throws,NaN,NaN,Sr.,"Lower Gwynedd, Pa.",Germantown Academy,2023,"lower gwynedd, pennsylvania"
8848,Fieke Van der Kamp,track-and-field,Harvard,Distance,NaN,NaN,Fy,"Victoria, Australia",Nillumbuk High School,2023,"victoria, australia"
8849,Abby Weber,track-and-field,Harvard,Distance,NaN,NaN,Fy,"Chapel Hill, N.C.",Chapel Hill High School,2023,"chapel hill, north carolina"
8850,Milina Wepiwé,track-and-field,Harvard,Throws,NaN,NaN,Fy,"Friedrichsdorf, Germany",Kaiserin-Friedrich Gymnasium,2023,"friedrichsdorf, germany"

In [7]:
df[['city', 'state']] = df['std_city_name'].str.split(',', 1, expand=True)
df['state'] = df['state'].str.lstrip()

In [8]:
df

,Name,Sport,College,Position,Height,Weight,Academic Year,Hometown,High School,Year,std_city_name,city,state
0,Zezo Beshir,mens-track-and-field,University of Pennsylvania,Throws,NaN,NaN,Fr.,"Newton, Mass.",Newton South,2023,"newton, massachusetts",newton,massachusetts
1,Alex Boyko,mens-track-and-field,University of Pennsylvania,Distance,NaN,NaN,Fr.,"Cinnaminson, N.J.",Cinnaminson,2023,"cinnaminson, new jersey",cinnaminson,new jersey
2,Titus Bretzke,mens-track-and-field,University of Pennsylvania,Mid-Distance,NaN,NaN,Jr.,"Greenville, Mich.",Greenville,2023,"greenville, michigan",greenville,michigan
3,Nick Carpenter,mens-track-and-field,University of Pennsylvania,Distance,NaN,NaN,So.,"Winter Park, Fla.",Trinity Prep,2023,"winter park, florida",winter park,florida
4,Elijah Cook,mens-track-and-field,University of Pennsylvania,Throws,NaN,NaN,Jr.,"Bedford, Pa.",Bedford,2023,"bedford, pennsylvania",bedford,pennsylvania
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8846,Cara Salsberry,track-and-field,Harvard,Throws,NaN,NaN,Jr.,"Boynton Beach, Fla.",Somerset Academy Canyons,2023,"boynton beach, florida",boynton beach,florida
8847,Meaghan Toscano,track-and-field,Harvard,Throws,NaN,NaN,Sr.,"Lower Gwynedd, Pa.",Germantown Academy,2023,"lower gwynedd, pennsylvania",lower gwynedd,pennsylvania
8848,Fieke Van der Kamp,track-and-field,Harvard,Distance,NaN,NaN,Fy,"Victoria, Australia",Nillumbuk High School,2023,"victoria, australia",victoria,australia
8849,Abby Weber,track-and-field,Harvard,Distance,NaN,NaN,Fy,"Chapel Hill, N.C.",Chapel Hill High School,2023,"chapel hill, north carolina",chapel hill,north carolina
8850,Milina Wepiwé,track-and-field,Harvard,Throws,NaN,NaN,Fy,"Friedrichsdorf, Germany",Kaiserin-Friedrich Gymnasium,2023,"friedrichsdorf, germany",friedrichsdorf,germany

In [9]:
lf = df['state'].value_counts()

In [10]:
lf.to_dict()

{'california': 1115,
 'new jersey': 766,
 'pennsylvania': 758,
 'massachusetts': 502,
 'new york': 501,
 'texas': 446,
 'florida': 349,
 'georgia': 344,
 'illinois': 306,
 'maryland': 260,
 'ohio': 233,
 'virginia': 180,
 'connecticut': 170,
 'north carolina': 153,
 'michigan': 142,
 'washington': 133,
 'colorado': 108,
 'indiana': 90,
 'ontario': 82,
 'minnesota': 80,
 'tennessee': 75,
 'arizona': 74,
 'alabama': 67,
 'district of columbia': 61,
 'del.': 53,
 'england': 45,
 'louisiana': 39,
 'missouri': 39,
 'oregon': 39,
 'u.k.': 38,
 'south carolina': 35,
 'hawaii': 34,
 'wisconsin': 33,
 'germany': 32,
 'new hampshire': 32,
 'rhode island': 31,
 'utah': 27,
 'kansas': 25,
 'united kingdom': 24,
 'maine': 21,
 'oklahoma': 21,
 'australia': 20,
 'sweden': 20,
 'ark.': 20,
 'idaho': 20,
 'norway': 20,
 'iceland': 16,
 'israel': 16,
 'ont.': 16,
 'nevada': 15,
 'nigeria': 13,
 'british columbia': 12,
 'mont.': 12,
 'new zealand': 12,
 'iowa': 12,
 'france': 11,
 'canada': 11,
 'texas.': 11,
 'ireland': 9,
 'quebec': 9,
 'serbia': 9,
 'slovakia': 9,
 'scotland': 9,
 'que.': 9,
 'b.c.': 9,
 'w.va.': 9,
 'kentucky': 8,
 'neb.': 8,
 'czech republic': 8,
 'wisc.': 8,
 'denmark': 7,
 'japan': 7,
 'new mexico': 7,
 'penn.': 6,
 'greece': 6,
 'luxembourg': 5,
 'costa rica': 5,
 'ethiopia': 5,
 'jamaica': 5,
 'ny': 5,
 'switzerland': 5,
 'cyprus': 4,
 'ghana': 4,
 'or.': 4,
 'barbados': 4,
 'ct.': 4,
 'oh': 4,
 'slovak republic': 4,
 'ga': 4,
 'il.': 4,
 'wash': 4,
 'mexico': 4,
 'or': 4,
 'victoria (australia)': 4,
 'shanxi (china)': 4,
 'surrey': 4,
 'wva.': 4,
 'cameroon': 4,
 'poland': 4,
 'wa.': 4,
 'qatar': 4,
 'puerto rico': 4,
 'spain': 4,
 'taiwan': 4,
 'vermont': 3,
 'ks': 3,
 'il': 3,
 'finland': 3,
 'tex.': 3,
 'south africa': 3,
 'sask.': 2,
 'western australia': 2,
 'north dakota': 2,
 'romania': 2,
 'ill.': 2,
 'the netherlands': 2,
 'croatia': 2,
 'belgium': 2,
 'italy': 2,
 'fl.': 2,
 'turkey': 2,
 'hungary': 2,
 'benin': 2,
 'lesotho': 2,
 'lithuania': 1,
 'new south wales': 1,
 'philippines': 1,
 'calif': 1,
 'brazil': 1,
 'miss.': 1,
 'alberta': 1,
 'clackmannanshire': 1}

In [11]:
df

,Name,Sport,College,Position,Height,Weight,Academic Year,Hometown,High School,Year,std_city_name,city,state
0,Zezo Beshir,mens-track-and-field,University of Pennsylvania,Throws,NaN,NaN,Fr.,"Newton, Mass.",Newton South,2023,"newton, massachusetts",newton,massachusetts
1,Alex Boyko,mens-track-and-field,University of Pennsylvania,Distance,NaN,NaN,Fr.,"Cinnaminson, N.J.",Cinnaminson,2023,"cinnaminson, new jersey",cinnaminson,new jersey
2,Titus Bretzke,mens-track-and-field,University of Pennsylvania,Mid-Distance,NaN,NaN,Jr.,"Greenville, Mich.",Greenville,2023,"greenville, michigan",greenville,michigan
3,Nick Carpenter,mens-track-and-field,University of Pennsylvania,Distance,NaN,NaN,So.,"Winter Park, Fla.",Trinity Prep,2023,"winter park, florida",winter park,florida
4,Elijah Cook,mens-track-and-field,University of Pennsylvania,Throws,NaN,NaN,Jr.,"Bedford, Pa.",Bedford,2023,"bedford, pennsylvania",bedford,pennsylvania
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8846,Cara Salsberry,track-and-field,Harvard,Throws,NaN,NaN,Jr.,"Boynton Beach, Fla.",Somerset Academy Canyons,2023,"boynton beach, florida",boynton beach,florida
8847,Meaghan Toscano,track-and-field,Harvard,Throws,NaN,NaN,Sr.,"Lower Gwynedd, Pa.",Germantown Academy,2023,"lower gwynedd, pennsylvania",lower gwynedd,pennsylvania
8848,Fieke Van der Kamp,track-and-field,Harvard,Distance,NaN,NaN,Fy,"Victoria, Australia",Nillumbuk High School,2023,"victoria, australia",victoria,australia
8849,Abby Weber,track-and-field,Harvard,Distance,NaN,NaN,Fy,"Chapel Hill, N.C.",Chapel Hill High School,2023,"chapel hill, north carolina",chapel hill,north carolina
8850,Milina Wepiwé,track-and-field,Harvard,Throws,NaN,NaN,Fy,"Friedrichsdorf, Germany",Kaiserin-Friedrich Gymnasium,2023,"friedrichsdorf, germany",friedrichsdorf,germany

In [13]:
df.to_csv("jack_final_df.csv")