In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

In [2]:
all_years_players = pd.DataFrame()
sports = ['mens-basketball', 'womens-basketball', 'womens-track-and-field', 'mens-track-and-field']
oneyr_sports = ["football", 'womens-volleyball', 'womens-soccer', 'mens-soccer']
track =  'mens-track-and-field' # 2 tables on same page; one for mens, one for womens

years = range(2010, 2025, 1)

for sport in sports:
    for year in years:
        if year == 2024:
            print(year - 1, sport)
            yeardf = pd.read_html(f"https://pennathletics.com/sports/{sport}/roster?view=2")[2]
            yeardf['year'] = year - 1
            yeardf['sport'] = sport
            #print(yeardf.head())
            all_years_players = pd.concat([ yeardf, all_years_players], ignore_index=True)
        else:
            print(year, sport)
            yeardf = pd.read_html(f"https://pennathletics.com/sports/{sport}/roster/{year-1}-{year-2000}?view=2")[2]
            yeardf['year'] = year - 1
            yeardf['sport'] = sport
            #print(yeardf.head())
            all_years_players = pd.concat([ yeardf, all_years_players], ignore_index=True)

2010 mens-basketball
2011 mens-basketball
2012 mens-basketball
2013 mens-basketball
2014 mens-basketball
2015 mens-basketball
2016 mens-basketball
2017 mens-basketball
2018 mens-basketball
2019 mens-basketball
2020 mens-basketball
2021 mens-basketball
2022 mens-basketball
2023 mens-basketball
2023 mens-basketball
2010 womens-basketball
2011 womens-basketball
2012 womens-basketball
2013 womens-basketball
2014 womens-basketball
2015 womens-basketball
2016 womens-basketball
2017 womens-basketball
2018 womens-basketball
2019 womens-basketball
2020 womens-basketball
2021 womens-basketball
2022 womens-basketball
2023 womens-basketball
2023 womens-basketball
2010 womens-track-and-field
2011 womens-track-and-field
2012 womens-track-and-field
2013 womens-track-and-field
2014 womens-track-and-field
2015 womens-track-and-field
2016 womens-track-and-field
2017 womens-track-and-field
2018 womens-track-and-field
2019 womens-track-and-field
2020 womens-track-and-field
2021 womens-track-and-field
2022 womens-track-and-field
2023 womens-track-and-field
2023 womens-track-and-field
2010 mens-track-and-field
2011 mens-track-and-field
2012 mens-track-and-field
2013 mens-track-and-field
2014 mens-track-and-field
2015 mens-track-and-field
2016 mens-track-and-field
2017 mens-track-and-field
2018 mens-track-and-field
2019 mens-track-and-field
2020 mens-track-and-field
2021 mens-track-and-field
2022 mens-track-and-field
2023 mens-track-and-field
2023 mens-track-and-field

In [3]:
for sport in oneyr_sports:
    for year in range(2010, 2024, 1):
            print(year - 1, sport)
            yeardf = pd.read_html(f"https://pennathletics.com/sports/{sport}/roster/{year}?view=2")[2]
            yeardf['year'] = year - 1
            yeardf['sport'] = sport
            all_years_players = pd.concat([all_years_players, yeardf], ignore_index = True)

2009 football
2010 football
2011 football
2012 football
2013 football
2014 football
2015 football
2016 football
2017 football
2018 football
2019 football
2020 football
2021 football
2022 football
2009 womens-volleyball
2010 womens-volleyball
2011 womens-volleyball
2012 womens-volleyball
2013 womens-volleyball
2014 womens-volleyball
2015 womens-volleyball
2016 womens-volleyball
2017 womens-volleyball
2018 womens-volleyball
2019 womens-volleyball
2020 womens-volleyball
2021 womens-volleyball
2022 womens-volleyball
2009 womens-soccer
2010 womens-soccer
2011 womens-soccer
2012 womens-soccer
2013 womens-soccer
2014 womens-soccer
2015 womens-soccer
2016 womens-soccer
2017 womens-soccer
2018 womens-soccer
2019 womens-soccer
2020 womens-soccer
2021 womens-soccer
2022 womens-soccer
2009 mens-soccer
2010 mens-soccer
2011 mens-soccer
2012 mens-soccer
2013 mens-soccer
2014 mens-soccer
2015 mens-soccer
2016 mens-soccer
2017 mens-soccer
2018 mens-soccer
2019 mens-soccer
2020 mens-soccer
2021 mens-soccer
2022 mens-soccer

In [4]:
all_years_players

,Name,Pos.,Year,Hometown / High School,year,sport,#,Full Name,Pos,Ht.,Academic Year,Wt.,C,Hometown/High School,Pronouns
0,Zezo Beshir,Throws,Fr.,"Newton, Mass. / Newton South",2023,mens-track-and-field,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alex Boyko,Distance,Fr.,"Cinnaminson, N.J. / Cinnaminson",2023,mens-track-and-field,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Titus Bretzke,Mid-Distance,Jr.,"Greenville, Mich. / Greenville",2023,mens-track-and-field,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nick Carpenter,Distance,So.,"Winter Park, Fla. / Trinity Prep",2023,mens-track-and-field,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Elijah Cook,Throws,Jr.,"Bedford, Pa. / Bedford",2023,mens-track-and-field,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4722,Patrick Cayelli,M,So.,"Anderson, S.C. / T.L. Hanna (Carolina Elite Ac...",2022,mens-soccer,31.0,NaN,NaN,5-10,NaN,NaN,NaN,NaN,NaN
4723,Jacob Muchnick,M,Sr.,"Menlo Park, Calif. / Menlo Park (De Anza Force...",2022,mens-soccer,32.0,NaN,NaN,5-8,NaN,NaN,NaN,NaN,NaN
4724,Adam Kuechler,F,Fr.,"Needham, Mass. / Roxbury Latin School (New Eng...",2022,mens-soccer,33.0,NaN,NaN,6-2,NaN,NaN,NaN,NaN,NaN
4725,Owen Sullivan,D,Fr.,"Bay Village, Ohio / Saint Ignatius (Spire FC)",2022,mens-soccer,34.0,NaN,NaN,5-11,NaN,NaN,NaN,NaN,NaN
4726,Will Kelly,M,So.,"Rochester, N.Y. / Brighton (Empire United)",2022,mens-soccer,35.0,NaN,NaN,5-8,NaN,NaN,NaN,NaN,NaN

In [5]:
all_years_players.to_csv("Penn.csv")

In [6]:
# for year in range(2016,2025,1):
#     mens_track = pd.read_html(f"https://gocrimson.com/sports/mens-track-and-field/roster/{year-1}-{year-2000}?view=2")[3]
#     womens_track = pd.read_html(f"https://gocrimson.com/sports/mens-track-and-field/roster/{year-1}-{year-2000}?view=2")[2]
#     mens_track["Sport"] = "track-and-field"
#     womens_track["Sport"] = "track-and-field"
#     mens_track["Year"] = year-1
#     womens_track["Year"] = year-1
#     print(year)
    
#     all_years_players = pd.concat([all_years_players, mens_track, womens_track], ignore_index = True)